require("dotenv").config();
const {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,PermissionFlagsBits}=require("discord.js");
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const matches=new Map(), INACTIVITY_MS=180000;
const commands=[
 new SlashCommandBuilder().setName("painel").setDescription("Cria uma fila de aposta.")
 .addStringOption(o=>o.setName("valor").setDescription("Valor por jogador").setRequired(true))
 .addStringOption(o=>o.setName("modo").setDescription("Modo").setRequired(true).addChoices({name:"1v1",value:"1v1"},{name:"2v2",value:"2v2"},{name:"3v3",value:"3v3"}))
 .addStringOption(o=>o.setName("plataforma").setDescription("Plataforma").setRequired(true).addChoices({name:"PC",value:"PC"},{name:"Mobile",value:"Mobile"},{name:"Misto",value:"Misto"}))
 .addStringOption(o=>o.setName("mensagem").setDescription("Mensagem").setRequired(true)),
 new SlashCommandBuilder().setName("cancelar").setDescription("Cancela a partida e fecha o canal.")
];
const staff=m=>m.permissions.has(PermissionFlagsBits.ManageChannels)||m.permissions.has(PermissionFlagsBits.Administrator);
const qembed=m=>new EmbedBuilder().setTitle("🎯 APOSTA").setDescription(m.message).addFields({name:"🪙 Valor (por jogador)",value:`\`${m.value}\``},{name:"⚔️ Modo",value:`**${m.mode}**`,inline:true},{name:"📱 Plataforma",value:`**${m.platform}**`,inline:true},{name:"🎮 Jogadores na fila",value:m.players.length?m.players.map((x,i)=>`${i+1}. <@${x}>`).join("\n"):"_Ninguém na fila ainda_"}).setColor(0x2ecc71);
const qbuttons=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("join").setLabel("Entrar na aposta").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("leave").setLabel("Sair").setStyle(ButtonStyle.Danger))];
const fembed=m=>new EmbedBuilder().setTitle("🎮 Partida encontrada!").setDescription(`**Mapa:** ${m.message} • **Modo:** ${m.mode} • **Plataforma:** ${m.platform}\n**Valor (por jogador):** ${m.value}\n**Mediador:** <@${m.mediator}>`).addFields({name:"🔵 Time 1",value:m.t1.map(x=>`<@${x}>`).join("\n"),inline:true},{name:"🔴 Time 2",value:m.t2.map(x=>`<@${x}>`).join("\n"),inline:true},{name:"📜 Regras",value:"• Md3\n• Full Soco ou o Emote que preferirem\n• Colocar códigos no chat e pontuação\n• Mapa escolhido: "+m.message}).setColor(0x2b2d31);
const wbuttons=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("w1").setLabel("Venceu: Time 1").setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId("w2").setLabel("Venceu: Time 2").setStyle(ButtonStyle.Success))];
async function close(ch,r){await ch.send(`🔒 **Canal encerrado.**\n${r}`).catch(()=>{});setTimeout(()=>ch.delete("Partida encerrada").catch(()=>{}),1000)}
function watch(m){m.last=Date.now();m.timer=setInterval(async()=>{if(m.closed)return clearInterval(m.timer);if(Date.now()-m.last>=INACTIVITY_MS){let c=await client.channels.fetch(m.channel).catch(()=>null);if(c)await c.send("⚠️ **3 minutos sem atividade.** Se houver jogador offline, sem resposta ou sem Pix, a staff pode usar `/cancelar`.").catch(()=>{});m.last=Date.now()}},15000)}
client.once("ready",async()=>{console.log(`✅ ${client.user.tag} online!`);let r=new REST({version:"10"}).setToken(process.env.DISCORD_TOKEN);try{await r.put(process.env.GUILD_ID?Routes.applicationGuildCommands(client.user.id,process.env.GUILD_ID):Routes.applicationCommands(client.user.id),{body:commands.map(x=>x.toJSON())});console.log("✅ Comandos registrados.")}catch(e){console.error(e)}});
client.on("interactionCreate",async i=>{try{
 if(i.isChatInputCommand()&&i.commandName==="painel"){let m={channel:i.channelId,mediator:i.user.id,value:i.options.getString("valor"),mode:i.options.getString("modo"),platform:i.options.getString("plataforma"),message:i.options.getString("mensagem"),max:Number(i.options.getString("modo")[0])*2,players:[],t1:[],t2:[],closed:false};let msg=await i.channel.send({embeds:[qembed(m)],components:qbuttons()});m.msg=msg.id;matches.set(msg.id,m);watch(m);return i.reply({content:"✅ Painel de aposta criado.",ephemeral:true})}
 if(i.isChatInputCommand()&&i.commandName==="cancelar"){if(!staff(i.member))return i.reply({content:"❌ Apenas staff pode usar este comando.",ephemeral:true});let m=[...matches.values()].find(x=>x.channel===i.channelId&&!x.closed);if(!m)return i.reply({content:"❌ Não há uma partida ativa neste canal.",ephemeral:true});m.closed=true;clearInterval(m.timer);await i.reply({content:"🔒 Partida cancelada. Fechando o canal...",ephemeral:true});return close(i.channel,"A staff cancelou a partida.")}
 if(i.isButton()){let m=[...matches.values()].find(x=>x.channel===i.channelId&&!x.closed);if(!m)return i.reply({content:"❌ Esta partida não está ativa.",ephemeral:true});m.last=Date.now();
  if(i.customId==="join"){if(m.players.includes(i.user.id))return i.reply({content:"Você já está na fila.",ephemeral:true});if(m.players.length>=m.max)return i.reply({content:"❌ A fila está cheia.",ephemeral:true});m.players.push(i.user.id);if(m.players.length===m.max){let h=m.max/2;m.t1=m.players.slice(0,h);m.t2=m.players.slice(h);await i.update({embeds:[fembed(m)],components:wbuttons()});return i.channel.send("🎮 **Partida encontrada!** Joguem e enviem o print do resultado aqui.\n🔐 **Apenas staff pode votar no vencedor.**")}return i.update({embeds:[qembed(m)],components:qbuttons()})}
  if(i.customId==="leave"){let n=m.players.indexOf(i.user.id);if(n<0)return i.reply({content:"Você não está na fila.",ephemeral:true});m.players.splice(n,1);return i.update({embeds:[qembed(m)],components:qbuttons()})}
  if(i.customId==="w1"||i.customId==="w2"){if(!staff(i.member))return i.reply({content:"❌ Apenas staff pode votar.",ephemeral:true});let w=i.customId==="w1"?"Time 1":"Time 2";return i.reply({content:`🏆 **${w} venceu!** Resultado confirmado pela staff.`})}
 }}catch(e){console.error(e);if(!i.replied&&!i.deferred)i.reply({content:"❌ Ocorreu um erro.",ephemeral:true}).catch(()=>{})}});
client.login(process.env.DISCORD_TOKEN);
